In [4]:
from flask import Flask, request, jsonify
import numpy as np
from keras.preprocessing.sequence import pad_sequences
import pickle

# Max input length (max number of words) 
max_seq_len = 500

class_names = ['Happy', 'Fear', 'Angry', 'Sad']

model = pickle.load(open('./text_model.pickle', 'rb'))
tokenizer = pickle.load(open('./tokenizer.pickle', 'rb'))

app = Flask(__name__)

@app.route('/getmood', methods=['GET'])
def get_mood():
    input = request.args.get('input')
    message = [input]
    print(message)
    # message = ['I am sad']

    seq = tokenizer.texts_to_sequences(message)
    padded = pad_sequences(seq, maxlen=max_seq_len)
    pred = model.predict(padded)

    print(pred)

    output = class_names[np.argmax(pred)]
    data = {
        'message': message,
        'mood': output
    }
    print(output)
    return jsonify(data)

if __name__ == '__main__':
    app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Mar/2022 13:20:08] "GET /getmood?input=i%20am%20exhausted HTTP/1.1" 200 -


['i am exhausted']
[[0.17522897 0.01076579 0.00910508 0.8049002 ]]
Sad


127.0.0.1 - - [29/Mar/2022 13:20:09] "GET /getmood?input=i%20am%20exhausted HTTP/1.1" 200 -


['i am exhausted']
[[0.17522897 0.01076579 0.00910508 0.8049002 ]]
Sad


127.0.0.1 - - [29/Mar/2022 13:48:42] "GET /getmood?input=Yes%20,%20he%20was%20.%20I%27m%20not%20imagining%20it.Finally%20,%20just%20when%20I%20got%20home%20,%20I%20turned%20around%20and%20looked%20at%20him.He%20was%20just%20standing%20there%20.%20He%20didn%27t%20smile%20.%20He%20just%20stood%20there%20.%20It%20was%20so%20obvious.What%20should%20I%20do%20?%20I%27m%20so%20scared%20.%20Can%20I%20call%20the%20police%20? HTTP/1.1" 200 -


["Yes , he was . I'm not imagining it.Finally , just when I got home , I turned around and looked at him.He was just standing there . He didn't smile . He just stood there . It was so obvious.What should I do ? I'm so scared . Can I call the police ?"]
[[1.1988644e-02 9.8204881e-01 7.8511430e-04 5.1774425e-03]]
Fear


127.0.0.1 - - [29/Mar/2022 13:48:56] "GET /getmood?input=Yes%20,%20he%20was%20.%20I%27m%20not%20imagining%20it.Finally%20,%20just%20when%20I%20got%20home%20,%20I%20turned%20around%20and%20looked%20at%20him.He%20was%20just%20standing%20there%20.%20He%20didn%27t%20smile%20.%20He%20just%20stood%20there%20.%20It%20was%20so%20obvious.What%20should%20I%20do%20?%20I%27m%20so%20scared%20.%20Can%20I%20call%20the%20police%20? HTTP/1.1" 200 -


["Yes , he was . I'm not imagining it.Finally , just when I got home , I turned around and looked at him.He was just standing there . He didn't smile . He just stood there . It was so obvious.What should I do ? I'm so scared . Can I call the police ?"]
[[1.1988644e-02 9.8204881e-01 7.8511430e-04 5.1774425e-03]]
Fear


127.0.0.1 - - [29/Mar/2022 13:49:34] "GET /getmood?input=She%20looked%20a%20little%20less%20resentful%20than%20earlier%20,%20and%20--%20dare%20he%20hope%20it%20?%20--%20even%20slightly%20anxious%20for%20him%20. HTTP/1.1" 200 -


['She looked a little less resentful than earlier , and -- dare he hope it ? -- even slightly anxious for him .']
[[9.0204441e-04 4.7236733e-02 9.3082005e-01 2.1041097e-02]]
Angry


127.0.0.1 - - [29/Mar/2022 13:49:35] "GET /getmood?input=She%20looked%20a%20little%20less%20resentful%20than%20earlier%20,%20and%20--%20dare%20he%20hope%20it%20?%20--%20even%20slightly%20anxious%20for%20him%20. HTTP/1.1" 200 -


['She looked a little less resentful than earlier , and -- dare he hope it ? -- even slightly anxious for him .']
[[9.0204441e-04 4.7236733e-02 9.3082005e-01 2.1041097e-02]]
Angry


127.0.0.1 - - [29/Mar/2022 13:56:35] "GET /getmood?input=You%20won%20%E2%80%99%20t%20believe%20who%20%E2%80%99%20s%20been%20elected%20to%20do%20overtime%20on%20the%20Baker%20account%20!%20Me%20!%20I%20%E2%80%99%20Ve%20already%20logged%20in%2020%20hours%20of%20overtime%20! HTTP/1.1" 200 -


['You won ’ t believe who ’ s been elected to do overtime on the Baker account ! Me ! I ’ Ve already logged in 20 hours of overtime !']
[[0.0463168  0.00115485 0.9401953  0.01233311]]
Angry


127.0.0.1 - - [29/Mar/2022 13:56:36] "GET /getmood?input=You%20won%20%E2%80%99%20t%20believe%20who%20%E2%80%99%20s%20been%20elected%20to%20do%20overtime%20on%20the%20Baker%20account%20!%20Me%20!%20I%20%E2%80%99%20Ve%20already%20logged%20in%2020%20hours%20of%20overtime%20! HTTP/1.1" 200 -


['You won ’ t believe who ’ s been elected to do overtime on the Baker account ! Me ! I ’ Ve already logged in 20 hours of overtime !']
[[0.0463168  0.00115485 0.9401953  0.01233311]]
Angry


127.0.0.1 - - [29/Mar/2022 13:57:07] "GET /getmood?input=I%20have%20to%20do%20lot%20of%20reviews%20today HTTP/1.1" 200 -


['I have to do lot of reviews today']
[[0.10868162 0.03150471 0.04041147 0.8194022 ]]
Sad


127.0.0.1 - - [29/Mar/2022 13:57:09] "GET /getmood?input=I%20have%20to%20do%20lot%20of%20reviews%20today HTTP/1.1" 200 -


['I have to do lot of reviews today']
[[0.10868162 0.03150471 0.04041147 0.8194022 ]]
Sad
